### ISSUE TITLE
Creating properties when using aliases

### ISSUE THREAD

**Issue by wolfkarl** [unxok/dataedit#7]
Editing or creating a property with an alias ("TABLE something AS sth") does not work. The property is created with the alias name instead (and then not read).

Otherwise great plugin, thanks to the developer!

**Comment by unxok** [comment]
As [stated in the read me](https://github.com/unxok/dataedit?tab=readme-ov-file#dataview-query) (maybe I should make it more obvious?), you indeed cannot do that:
> You cannot specify column aliases in the query

*You can however*, set up column aliases for properties on a general plugin setting or an individual blocks' config.

If you're curious on the reasoning of why it is this way: Datedit directly feeds your query to Dataview which returns two lists of data. One contains the column names (or aliases if you specify) and the other contains the corresponding values for the specified properties. Because that is the only information Dataedit has about the queried files, it has no way to tell what columns have aliases used for them and what their actual property names are. 

In the future, I plan on first reading the query to figure out what aliases are specified so using the separate settings in the plugin wouldn't be necessary anymore.

**Comment by wolfkarl** [comment]
My bad -- everything else went smoothly out of the box so I had no reason to look into the README 😄 

Thanks for the comprehensive answer!
